# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\dev\projects\ecs_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\dev\projects\ecs_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\dev\projects\ecs_test\CMakeFiles C:\dev\projects\ecs_test\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\dev\projects\ecs_test\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ECS_TEST

# Build rule for target.
ECS_TEST: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ECS_TEST
.PHONY : ECS_TEST

# fast build rule for target.
ECS_TEST/fast:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/build
.PHONY : ECS_TEST/fast

src/core/memory.obj: src/core/memory.cpp.obj

.PHONY : src/core/memory.obj

# target to build an object file
src/core/memory.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/core/memory.cpp.obj
.PHONY : src/core/memory.cpp.obj

src/core/memory.i: src/core/memory.cpp.i

.PHONY : src/core/memory.i

# target to preprocess a source file
src/core/memory.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/core/memory.cpp.i
.PHONY : src/core/memory.cpp.i

src/core/memory.s: src/core/memory.cpp.s

.PHONY : src/core/memory.s

# target to generate assembly for a file
src/core/memory.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/core/memory.cpp.s
.PHONY : src/core/memory.cpp.s

src/dataStructures/string.obj: src/dataStructures/string.cpp.obj

.PHONY : src/dataStructures/string.obj

# target to build an object file
src/dataStructures/string.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/dataStructures/string.cpp.obj
.PHONY : src/dataStructures/string.cpp.obj

src/dataStructures/string.i: src/dataStructures/string.cpp.i

.PHONY : src/dataStructures/string.i

# target to preprocess a source file
src/dataStructures/string.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/dataStructures/string.cpp.i
.PHONY : src/dataStructures/string.cpp.i

src/dataStructures/string.s: src/dataStructures/string.cpp.s

.PHONY : src/dataStructures/string.s

# target to generate assembly for a file
src/dataStructures/string.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/dataStructures/string.cpp.s
.PHONY : src/dataStructures/string.cpp.s

src/ecs/ecs.obj: src/ecs/ecs.cpp.obj

.PHONY : src/ecs/ecs.obj

# target to build an object file
src/ecs/ecs.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecs.cpp.obj
.PHONY : src/ecs/ecs.cpp.obj

src/ecs/ecs.i: src/ecs/ecs.cpp.i

.PHONY : src/ecs/ecs.i

# target to preprocess a source file
src/ecs/ecs.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecs.cpp.i
.PHONY : src/ecs/ecs.cpp.i

src/ecs/ecs.s: src/ecs/ecs.cpp.s

.PHONY : src/ecs/ecs.s

# target to generate assembly for a file
src/ecs/ecs.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecs.cpp.s
.PHONY : src/ecs/ecs.cpp.s

src/ecs/ecsComponent.obj: src/ecs/ecsComponent.cpp.obj

.PHONY : src/ecs/ecsComponent.obj

# target to build an object file
src/ecs/ecsComponent.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecsComponent.cpp.obj
.PHONY : src/ecs/ecsComponent.cpp.obj

src/ecs/ecsComponent.i: src/ecs/ecsComponent.cpp.i

.PHONY : src/ecs/ecsComponent.i

# target to preprocess a source file
src/ecs/ecsComponent.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecsComponent.cpp.i
.PHONY : src/ecs/ecsComponent.cpp.i

src/ecs/ecsComponent.s: src/ecs/ecsComponent.cpp.s

.PHONY : src/ecs/ecsComponent.s

# target to generate assembly for a file
src/ecs/ecsComponent.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecsComponent.cpp.s
.PHONY : src/ecs/ecsComponent.cpp.s

src/ecs/ecsSystem.obj: src/ecs/ecsSystem.cpp.obj

.PHONY : src/ecs/ecsSystem.obj

# target to build an object file
src/ecs/ecsSystem.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecsSystem.cpp.obj
.PHONY : src/ecs/ecsSystem.cpp.obj

src/ecs/ecsSystem.i: src/ecs/ecsSystem.cpp.i

.PHONY : src/ecs/ecsSystem.i

# target to preprocess a source file
src/ecs/ecsSystem.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecsSystem.cpp.i
.PHONY : src/ecs/ecsSystem.cpp.i

src/ecs/ecsSystem.s: src/ecs/ecsSystem.cpp.s

.PHONY : src/ecs/ecsSystem.s

# target to generate assembly for a file
src/ecs/ecsSystem.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/ecs/ecsSystem.cpp.s
.PHONY : src/ecs/ecsSystem.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math/aabb.obj: src/math/aabb.cpp.obj

.PHONY : src/math/aabb.obj

# target to build an object file
src/math/aabb.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/aabb.cpp.obj
.PHONY : src/math/aabb.cpp.obj

src/math/aabb.i: src/math/aabb.cpp.i

.PHONY : src/math/aabb.i

# target to preprocess a source file
src/math/aabb.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/aabb.cpp.i
.PHONY : src/math/aabb.cpp.i

src/math/aabb.s: src/math/aabb.cpp.s

.PHONY : src/math/aabb.s

# target to generate assembly for a file
src/math/aabb.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/aabb.cpp.s
.PHONY : src/math/aabb.cpp.s

src/math/color.obj: src/math/color.cpp.obj

.PHONY : src/math/color.obj

# target to build an object file
src/math/color.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/color.cpp.obj
.PHONY : src/math/color.cpp.obj

src/math/color.i: src/math/color.cpp.i

.PHONY : src/math/color.i

# target to preprocess a source file
src/math/color.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/color.cpp.i
.PHONY : src/math/color.cpp.i

src/math/color.s: src/math/color.cpp.s

.PHONY : src/math/color.s

# target to generate assembly for a file
src/math/color.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/color.cpp.s
.PHONY : src/math/color.cpp.s

src/math/matrix.obj: src/math/matrix.cpp.obj

.PHONY : src/math/matrix.obj

# target to build an object file
src/math/matrix.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/matrix.cpp.obj
.PHONY : src/math/matrix.cpp.obj

src/math/matrix.i: src/math/matrix.cpp.i

.PHONY : src/math/matrix.i

# target to preprocess a source file
src/math/matrix.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/matrix.cpp.i
.PHONY : src/math/matrix.cpp.i

src/math/matrix.s: src/math/matrix.cpp.s

.PHONY : src/math/matrix.s

# target to generate assembly for a file
src/math/matrix.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/matrix.cpp.s
.PHONY : src/math/matrix.cpp.s

src/math/plane.obj: src/math/plane.cpp.obj

.PHONY : src/math/plane.obj

# target to build an object file
src/math/plane.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/plane.cpp.obj
.PHONY : src/math/plane.cpp.obj

src/math/plane.i: src/math/plane.cpp.i

.PHONY : src/math/plane.i

# target to preprocess a source file
src/math/plane.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/plane.cpp.i
.PHONY : src/math/plane.cpp.i

src/math/plane.s: src/math/plane.cpp.s

.PHONY : src/math/plane.s

# target to generate assembly for a file
src/math/plane.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/plane.cpp.s
.PHONY : src/math/plane.cpp.s

src/math/quaternion.obj: src/math/quaternion.cpp.obj

.PHONY : src/math/quaternion.obj

# target to build an object file
src/math/quaternion.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/quaternion.cpp.obj
.PHONY : src/math/quaternion.cpp.obj

src/math/quaternion.i: src/math/quaternion.cpp.i

.PHONY : src/math/quaternion.i

# target to preprocess a source file
src/math/quaternion.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/quaternion.cpp.i
.PHONY : src/math/quaternion.cpp.i

src/math/quaternion.s: src/math/quaternion.cpp.s

.PHONY : src/math/quaternion.s

# target to generate assembly for a file
src/math/quaternion.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/quaternion.cpp.s
.PHONY : src/math/quaternion.cpp.s

src/math/sphere.obj: src/math/sphere.cpp.obj

.PHONY : src/math/sphere.obj

# target to build an object file
src/math/sphere.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/sphere.cpp.obj
.PHONY : src/math/sphere.cpp.obj

src/math/sphere.i: src/math/sphere.cpp.i

.PHONY : src/math/sphere.i

# target to preprocess a source file
src/math/sphere.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/sphere.cpp.i
.PHONY : src/math/sphere.cpp.i

src/math/sphere.s: src/math/sphere.cpp.s

.PHONY : src/math/sphere.s

# target to generate assembly for a file
src/math/sphere.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/sphere.cpp.s
.PHONY : src/math/sphere.cpp.s

src/math/transform.obj: src/math/transform.cpp.obj

.PHONY : src/math/transform.obj

# target to build an object file
src/math/transform.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/transform.cpp.obj
.PHONY : src/math/transform.cpp.obj

src/math/transform.i: src/math/transform.cpp.i

.PHONY : src/math/transform.i

# target to preprocess a source file
src/math/transform.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/transform.cpp.i
.PHONY : src/math/transform.cpp.i

src/math/transform.s: src/math/transform.cpp.s

.PHONY : src/math/transform.s

# target to generate assembly for a file
src/math/transform.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/transform.cpp.s
.PHONY : src/math/transform.cpp.s

src/math/vecmath.obj: src/math/vecmath.cpp.obj

.PHONY : src/math/vecmath.obj

# target to build an object file
src/math/vecmath.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/vecmath.cpp.obj
.PHONY : src/math/vecmath.cpp.obj

src/math/vecmath.i: src/math/vecmath.cpp.i

.PHONY : src/math/vecmath.i

# target to preprocess a source file
src/math/vecmath.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/vecmath.cpp.i
.PHONY : src/math/vecmath.cpp.i

src/math/vecmath.s: src/math/vecmath.cpp.s

.PHONY : src/math/vecmath.s

# target to generate assembly for a file
src/math/vecmath.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/vecmath.cpp.s
.PHONY : src/math/vecmath.cpp.s

src/math/vector.obj: src/math/vector.cpp.obj

.PHONY : src/math/vector.obj

# target to build an object file
src/math/vector.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/vector.cpp.obj
.PHONY : src/math/vector.cpp.obj

src/math/vector.i: src/math/vector.cpp.i

.PHONY : src/math/vector.i

# target to preprocess a source file
src/math/vector.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/vector.cpp.i
.PHONY : src/math/vector.cpp.i

src/math/vector.s: src/math/vector.cpp.s

.PHONY : src/math/vector.s

# target to generate assembly for a file
src/math/vector.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/math/vector.cpp.s
.PHONY : src/math/vector.cpp.s

src/platform/generic/cmwc4096.obj: src/platform/generic/cmwc4096.c.obj

.PHONY : src/platform/generic/cmwc4096.obj

# target to build an object file
src/platform/generic/cmwc4096.c.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/generic/cmwc4096.c.obj
.PHONY : src/platform/generic/cmwc4096.c.obj

src/platform/generic/cmwc4096.i: src/platform/generic/cmwc4096.c.i

.PHONY : src/platform/generic/cmwc4096.i

# target to preprocess a source file
src/platform/generic/cmwc4096.c.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/generic/cmwc4096.c.i
.PHONY : src/platform/generic/cmwc4096.c.i

src/platform/generic/cmwc4096.s: src/platform/generic/cmwc4096.c.s

.PHONY : src/platform/generic/cmwc4096.s

# target to generate assembly for a file
src/platform/generic/cmwc4096.c.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/generic/cmwc4096.c.s
.PHONY : src/platform/generic/cmwc4096.c.s

src/platform/generic/genericMemory.obj: src/platform/generic/genericMemory.cpp.obj

.PHONY : src/platform/generic/genericMemory.obj

# target to build an object file
src/platform/generic/genericMemory.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/generic/genericMemory.cpp.obj
.PHONY : src/platform/generic/genericMemory.cpp.obj

src/platform/generic/genericMemory.i: src/platform/generic/genericMemory.cpp.i

.PHONY : src/platform/generic/genericMemory.i

# target to preprocess a source file
src/platform/generic/genericMemory.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/generic/genericMemory.cpp.i
.PHONY : src/platform/generic/genericMemory.cpp.i

src/platform/generic/genericMemory.s: src/platform/generic/genericMemory.cpp.s

.PHONY : src/platform/generic/genericMemory.s

# target to generate assembly for a file
src/platform/generic/genericMemory.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/generic/genericMemory.cpp.s
.PHONY : src/platform/generic/genericMemory.cpp.s

src/platform/opengl/openGLRenderDevice.obj: src/platform/opengl/openGLRenderDevice.cpp.obj

.PHONY : src/platform/opengl/openGLRenderDevice.obj

# target to build an object file
src/platform/opengl/openGLRenderDevice.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/opengl/openGLRenderDevice.cpp.obj
.PHONY : src/platform/opengl/openGLRenderDevice.cpp.obj

src/platform/opengl/openGLRenderDevice.i: src/platform/opengl/openGLRenderDevice.cpp.i

.PHONY : src/platform/opengl/openGLRenderDevice.i

# target to preprocess a source file
src/platform/opengl/openGLRenderDevice.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/opengl/openGLRenderDevice.cpp.i
.PHONY : src/platform/opengl/openGLRenderDevice.cpp.i

src/platform/opengl/openGLRenderDevice.s: src/platform/opengl/openGLRenderDevice.cpp.s

.PHONY : src/platform/opengl/openGLRenderDevice.s

# target to generate assembly for a file
src/platform/opengl/openGLRenderDevice.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/opengl/openGLRenderDevice.cpp.s
.PHONY : src/platform/opengl/openGLRenderDevice.cpp.s

src/platform/sdl/sdlApplication.obj: src/platform/sdl/sdlApplication.cpp.obj

.PHONY : src/platform/sdl/sdlApplication.obj

# target to build an object file
src/platform/sdl/sdlApplication.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdlApplication.cpp.obj
.PHONY : src/platform/sdl/sdlApplication.cpp.obj

src/platform/sdl/sdlApplication.i: src/platform/sdl/sdlApplication.cpp.i

.PHONY : src/platform/sdl/sdlApplication.i

# target to preprocess a source file
src/platform/sdl/sdlApplication.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdlApplication.cpp.i
.PHONY : src/platform/sdl/sdlApplication.cpp.i

src/platform/sdl/sdlApplication.s: src/platform/sdl/sdlApplication.cpp.s

.PHONY : src/platform/sdl/sdlApplication.s

# target to generate assembly for a file
src/platform/sdl/sdlApplication.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdlApplication.cpp.s
.PHONY : src/platform/sdl/sdlApplication.cpp.s

src/platform/sdl/sdlWindow.obj: src/platform/sdl/sdlWindow.cpp.obj

.PHONY : src/platform/sdl/sdlWindow.obj

# target to build an object file
src/platform/sdl/sdlWindow.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdlWindow.cpp.obj
.PHONY : src/platform/sdl/sdlWindow.cpp.obj

src/platform/sdl/sdlWindow.i: src/platform/sdl/sdlWindow.cpp.i

.PHONY : src/platform/sdl/sdlWindow.i

# target to preprocess a source file
src/platform/sdl/sdlWindow.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdlWindow.cpp.i
.PHONY : src/platform/sdl/sdlWindow.cpp.i

src/platform/sdl/sdlWindow.s: src/platform/sdl/sdlWindow.cpp.s

.PHONY : src/platform/sdl/sdlWindow.s

# target to generate assembly for a file
src/platform/sdl/sdlWindow.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdlWindow.cpp.s
.PHONY : src/platform/sdl/sdlWindow.cpp.s

src/platform/sdl/sdltiming.obj: src/platform/sdl/sdltiming.cpp.obj

.PHONY : src/platform/sdl/sdltiming.obj

# target to build an object file
src/platform/sdl/sdltiming.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdltiming.cpp.obj
.PHONY : src/platform/sdl/sdltiming.cpp.obj

src/platform/sdl/sdltiming.i: src/platform/sdl/sdltiming.cpp.i

.PHONY : src/platform/sdl/sdltiming.i

# target to preprocess a source file
src/platform/sdl/sdltiming.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdltiming.cpp.i
.PHONY : src/platform/sdl/sdltiming.cpp.i

src/platform/sdl/sdltiming.s: src/platform/sdl/sdltiming.cpp.s

.PHONY : src/platform/sdl/sdltiming.s

# target to generate assembly for a file
src/platform/sdl/sdltiming.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/platform/sdl/sdltiming.cpp.s
.PHONY : src/platform/sdl/sdltiming.cpp.s

src/rendering/arrayBitmap.obj: src/rendering/arrayBitmap.cpp.obj

.PHONY : src/rendering/arrayBitmap.obj

# target to build an object file
src/rendering/arrayBitmap.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/arrayBitmap.cpp.obj
.PHONY : src/rendering/arrayBitmap.cpp.obj

src/rendering/arrayBitmap.i: src/rendering/arrayBitmap.cpp.i

.PHONY : src/rendering/arrayBitmap.i

# target to preprocess a source file
src/rendering/arrayBitmap.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/arrayBitmap.cpp.i
.PHONY : src/rendering/arrayBitmap.cpp.i

src/rendering/arrayBitmap.s: src/rendering/arrayBitmap.cpp.s

.PHONY : src/rendering/arrayBitmap.s

# target to generate assembly for a file
src/rendering/arrayBitmap.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/arrayBitmap.cpp.s
.PHONY : src/rendering/arrayBitmap.cpp.s

src/rendering/ddstexture.obj: src/rendering/ddstexture.cpp.obj

.PHONY : src/rendering/ddstexture.obj

# target to build an object file
src/rendering/ddstexture.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/ddstexture.cpp.obj
.PHONY : src/rendering/ddstexture.cpp.obj

src/rendering/ddstexture.i: src/rendering/ddstexture.cpp.i

.PHONY : src/rendering/ddstexture.i

# target to preprocess a source file
src/rendering/ddstexture.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/ddstexture.cpp.i
.PHONY : src/rendering/ddstexture.cpp.i

src/rendering/ddstexture.s: src/rendering/ddstexture.cpp.s

.PHONY : src/rendering/ddstexture.s

# target to generate assembly for a file
src/rendering/ddstexture.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/ddstexture.cpp.s
.PHONY : src/rendering/ddstexture.cpp.s

src/rendering/indexedModel.obj: src/rendering/indexedModel.cpp.obj

.PHONY : src/rendering/indexedModel.obj

# target to build an object file
src/rendering/indexedModel.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/indexedModel.cpp.obj
.PHONY : src/rendering/indexedModel.cpp.obj

src/rendering/indexedModel.i: src/rendering/indexedModel.cpp.i

.PHONY : src/rendering/indexedModel.i

# target to preprocess a source file
src/rendering/indexedModel.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/indexedModel.cpp.i
.PHONY : src/rendering/indexedModel.cpp.i

src/rendering/indexedModel.s: src/rendering/indexedModel.cpp.s

.PHONY : src/rendering/indexedModel.s

# target to generate assembly for a file
src/rendering/indexedModel.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/indexedModel.cpp.s
.PHONY : src/rendering/indexedModel.cpp.s

src/rendering/modelLoader.obj: src/rendering/modelLoader.cpp.obj

.PHONY : src/rendering/modelLoader.obj

# target to build an object file
src/rendering/modelLoader.cpp.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/modelLoader.cpp.obj
.PHONY : src/rendering/modelLoader.cpp.obj

src/rendering/modelLoader.i: src/rendering/modelLoader.cpp.i

.PHONY : src/rendering/modelLoader.i

# target to preprocess a source file
src/rendering/modelLoader.cpp.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/modelLoader.cpp.i
.PHONY : src/rendering/modelLoader.cpp.i

src/rendering/modelLoader.s: src/rendering/modelLoader.cpp.s

.PHONY : src/rendering/modelLoader.s

# target to generate assembly for a file
src/rendering/modelLoader.cpp.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/modelLoader.cpp.s
.PHONY : src/rendering/modelLoader.cpp.s

src/rendering/staticLibs/stb_image.obj: src/rendering/staticLibs/stb_image.c.obj

.PHONY : src/rendering/staticLibs/stb_image.obj

# target to build an object file
src/rendering/staticLibs/stb_image.c.obj:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/staticLibs/stb_image.c.obj
.PHONY : src/rendering/staticLibs/stb_image.c.obj

src/rendering/staticLibs/stb_image.i: src/rendering/staticLibs/stb_image.c.i

.PHONY : src/rendering/staticLibs/stb_image.i

# target to preprocess a source file
src/rendering/staticLibs/stb_image.c.i:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/staticLibs/stb_image.c.i
.PHONY : src/rendering/staticLibs/stb_image.c.i

src/rendering/staticLibs/stb_image.s: src/rendering/staticLibs/stb_image.c.s

.PHONY : src/rendering/staticLibs/stb_image.s

# target to generate assembly for a file
src/rendering/staticLibs/stb_image.c.s:
	$(MAKE) -f CMakeFiles\ECS_TEST.dir\build.make CMakeFiles/ECS_TEST.dir/src/rendering/staticLibs/stb_image.c.s
.PHONY : src/rendering/staticLibs/stb_image.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... ECS_TEST
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... src/core/memory.obj
	@echo ... src/core/memory.i
	@echo ... src/core/memory.s
	@echo ... src/dataStructures/string.obj
	@echo ... src/dataStructures/string.i
	@echo ... src/dataStructures/string.s
	@echo ... src/ecs/ecs.obj
	@echo ... src/ecs/ecs.i
	@echo ... src/ecs/ecs.s
	@echo ... src/ecs/ecsComponent.obj
	@echo ... src/ecs/ecsComponent.i
	@echo ... src/ecs/ecsComponent.s
	@echo ... src/ecs/ecsSystem.obj
	@echo ... src/ecs/ecsSystem.i
	@echo ... src/ecs/ecsSystem.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/math/aabb.obj
	@echo ... src/math/aabb.i
	@echo ... src/math/aabb.s
	@echo ... src/math/color.obj
	@echo ... src/math/color.i
	@echo ... src/math/color.s
	@echo ... src/math/matrix.obj
	@echo ... src/math/matrix.i
	@echo ... src/math/matrix.s
	@echo ... src/math/plane.obj
	@echo ... src/math/plane.i
	@echo ... src/math/plane.s
	@echo ... src/math/quaternion.obj
	@echo ... src/math/quaternion.i
	@echo ... src/math/quaternion.s
	@echo ... src/math/sphere.obj
	@echo ... src/math/sphere.i
	@echo ... src/math/sphere.s
	@echo ... src/math/transform.obj
	@echo ... src/math/transform.i
	@echo ... src/math/transform.s
	@echo ... src/math/vecmath.obj
	@echo ... src/math/vecmath.i
	@echo ... src/math/vecmath.s
	@echo ... src/math/vector.obj
	@echo ... src/math/vector.i
	@echo ... src/math/vector.s
	@echo ... src/platform/generic/cmwc4096.obj
	@echo ... src/platform/generic/cmwc4096.i
	@echo ... src/platform/generic/cmwc4096.s
	@echo ... src/platform/generic/genericMemory.obj
	@echo ... src/platform/generic/genericMemory.i
	@echo ... src/platform/generic/genericMemory.s
	@echo ... src/platform/opengl/openGLRenderDevice.obj
	@echo ... src/platform/opengl/openGLRenderDevice.i
	@echo ... src/platform/opengl/openGLRenderDevice.s
	@echo ... src/platform/sdl/sdlApplication.obj
	@echo ... src/platform/sdl/sdlApplication.i
	@echo ... src/platform/sdl/sdlApplication.s
	@echo ... src/platform/sdl/sdlWindow.obj
	@echo ... src/platform/sdl/sdlWindow.i
	@echo ... src/platform/sdl/sdlWindow.s
	@echo ... src/platform/sdl/sdltiming.obj
	@echo ... src/platform/sdl/sdltiming.i
	@echo ... src/platform/sdl/sdltiming.s
	@echo ... src/rendering/arrayBitmap.obj
	@echo ... src/rendering/arrayBitmap.i
	@echo ... src/rendering/arrayBitmap.s
	@echo ... src/rendering/ddstexture.obj
	@echo ... src/rendering/ddstexture.i
	@echo ... src/rendering/ddstexture.s
	@echo ... src/rendering/indexedModel.obj
	@echo ... src/rendering/indexedModel.i
	@echo ... src/rendering/indexedModel.s
	@echo ... src/rendering/modelLoader.obj
	@echo ... src/rendering/modelLoader.i
	@echo ... src/rendering/modelLoader.s
	@echo ... src/rendering/staticLibs/stb_image.obj
	@echo ... src/rendering/staticLibs/stb_image.i
	@echo ... src/rendering/staticLibs/stb_image.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

